### ISSUE TITLE
Production script?

### ISSUE THREAD

**Issue by sotojuan** [Widdershin/cycle-hot-reloading-example#2]
I know budo is for prototyping and stuff, but I was wondering if a production script (essentially babelify + uglify -> `bundle.js` and then serve with a server) could easily be written for this. I'm not very knowledgeable about Browserify. Thanks!

**Comment by Widdershin** [comment]
Sure! I usually use Github pages for my hosting. I can add an `npm run bundle` command and some instructions as to how to go about doing that.

I could also add an express server if you wanted to deploy to something like Heroku.

**Comment by sotojuan** [comment]
I'd honestly love both options, but either is fine. Thanks!

**Comment by Widdershin** [comment]
I've added instructions to the README about deploying to Github pages, as well as an `npm run bundle` command. I'll open an issue for an express server, but I might not get to it for a while. 

Let me know if that works for you :smile:

**Comment by sotojuan** [comment]
That looks perfect—will use it for my next Cycle project. Feel free to take your time with the Express one, this is good enough for now.

**Comment by Widdershin** [comment]
I'll close this for now, open a new issue if you run into any trouble!
